### PR TITLE
Add dedicated `SystemEventsLogger`

### PR DESCRIPTION
**Pull request by FantasyTeddy**
This change encapsulates all the logic considering the system-events inside a new `SystemEventsLogger` class.

### CODE REVIEW

**Comment by farmerbriantee** [comment]
Code gymnastics :( 
Lets get this release out and tested!!! no more changes like this please!

**Comment by FantasyTeddy** [comment]
What you call "code gymnastics", I call "applying best practices".
By encapsulating the logic of writing system-events into their own class, we could change the way the logging is actually done, by changing the implementation of the `SystemEventsLogger`, without affecting anything outside of it.
Originally, I planned to not make the `SystemEventsLogger` property `public` and pass it down to everyone that needs it. This would improve things even more, because it would reduce the dependency to the main `FormGPS`.

If you first want to get a release out, fine, don't merge my PR yet. But calling it "code gymnastics" and rejecting it makes me feel like you don't want any help at all...

**Comment by richardklasens** [comment]
Indeed. I reopened it. We can merge if the release is out and stable. The gymnastics Brian refers to is probably not the best word for it. I like your PR, so does he, but it’s just the wrong time. 

I would say, let’s create a group chat on Telegram with active contributors so we can talk first about our plans before we do a lot of work and then find out we end up in a million conflicts :)

cheers

**Comment by FantasyTeddy** [comment]
Thank you for reopening the PR!
I will gladly rebase it, once the release is out.

Maybe we could introduce the concept of release branches, such that work can continue on `develop` and does not need to be halted when a release is pending. (Especially, because I imagine that "after a release is before a release".)

However, for bigger changes with "millions of conflicts", it could indeed be beneficial to have a channel where this can be coordinated :)

**Pull request closed without merging**
