### PR TITLE
Use `Path.Combine` instead of string concatenation

### PR DESCRIPTION
**Pull request by FantasyTeddy**
By using [`Path.Combine`](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.combine) instead of string concatenations, we don't rely on Windows path separator (`\`) and would be compatible with platforms using `/` as well.

### CODE REVIEW

**Comment by richardklasens** [comment]
Maybe it’s better to change the workflow directly that the snippets of code aren’t in the designer files?

**Comment by FantasyTeddy** [comment]
If you mean that all custom logic should be in the `FormExample.cs` and not the `FormExample.Designer.cs` files, I absolutely agree.
Would you be interested if I would open a PR that would change this?

**Comment by farmerbriantee** [comment]
Needs to be rebased off the current dev changes

**Comment by FantasyTeddy** [comment]
Thanks for rebasing and merging.

**Comment by richardklasens** [comment]
I think there are more code snippets in designer files…

**Comment by FantasyTeddy** [comment]
What do you mean? Did I forget some string concatenations that should use `Path.Combine`?
Or do you refer to the `*.Designer.cs` files that contain custom logic? If so, I can fix this in a separate PR if you want.

**Pull request merged**
