### PR TITLE
Better packet reading.

### PR DESCRIPTION
**Pull request by MrPoke21**
Packet lenght fix.
Add new line separator.
Thread safe read.

Now fix UDP wifi lagg, and work in AGOpenGPS is very old tablet.

Required a arduino firmware packet correction.

### CODE REVIEW

**Comment by lansalot** [comment]
That's a lot to take in this time of night.. ;)

Why the CRLF on PGNs?

**Comment by MrPoke21** [comment]
My firs idea, readLine function. This is dont work good.
It is necessary to manage the fragmented packet.
AgIO read NEMA Panda this use new line. I think use this.

**Comment by mirh** [comment]
I seem to understand you only really did take a look at the UDP code. 
Is there any chance you could check the serial part too? I tested your PR early today, and it still didn't fix all the bad I reported in #303.

**Comment by MrPoke21** [comment]
> I seem to understand you only really did take a look at the UDP code. Is there any chance you could check the serial part too? I tested your PR early today, and it still didn't fix all the bad I reported in #303.

It is only client side. Need change teensy etc code..

**Comment by mirh** [comment]
Yes, the problem I was complaining about is client side (and it only pertains GPS data handling).

And my quick and dirty fix was for ParseNMEA to *not drop* the otherwise supposedly old sentences. 
Because (unlike UDP which doesn't even guarantee delivery) serial is FIFO and if you aren't fast enough pulling its data down, it can even pile up and block the flow. 

AgIO is doing something wrong with the way it sleeps between refreshes, but I cannot quite get to put my finger on it.

**Comment by lansalot** [comment]
Are you saying this code depends on firmware changes as well - which aren't supplied?

**Comment by MrPoke21** [comment]
Yes

**Comment by mirh** [comment]
I think it would really help if you could squash some of the duplicate commits, and reword them in english.

**Pull request closed without merging**
