### PR TITLE
Dual antenna support for SkyTraQ receivers

### PR DESCRIPTION
**Pull request by THiamu**
I added parsing of $PSTI,032,... messages sent from SkyTraQ receivers (for example PX1122R http://navspark.mybigcommerce.com/ns-hp-gn2-px1122r-breakout-board/) in Moving Base mode.

I already tested it on my work desk and I got some good looking data for roll and heading. Further tests on field I can do when my whole setup is done in late summer or maybe even later...

One receiver starts from 99$ (125$ as breakout board) and supports GPS L1/L2C, Galileo E1/E5b, Beidou B1I/B2I and GLONASS L1/L2. RTCM3/SkyTraQRawData input/output and NMEA output. This might get an alternative for the rtksimpleBoards for some others as well I think...
I added the datasheet from the receiver below.

THiamu
[PX1122R_DS.pdf](https://github.com/farmerbriantee/AgOpenGPS/files/4422703/PX1122R_DS.pdf)

### CODE REVIEW

**Comment by farmerbriantee** [comment]
Are you using this antenna? Do you have a working version with AgOpenGPS?

**Comment by farmerbriantee** [comment]
I've just manually added the code, its on the current AgOpenGPS Master branch. 

Would you post this project under GPS topic on the forum? Maybe some pics or video?

**Comment by THiamu** [comment]
Yes, I'm using these antennas, but at the moment I only have an bluetooth handheld RTK device built with this receiver. I'm planning to build a whole setup for one or two tractors across this summer.
I tested the code inside Visual Studio with a setup of two NS-HP-GN2 receivers on my working desk to get the $PSTI,032,... output and it worked so far (I got values for roll and heading which looked properly), but I cannot say anything about accuracy and reliability yet.
I can start a topic in the forum and introduce my project and this receiver, but pics or a video doesnt make sens at the moment.

**Comment by THiamu** [comment]
I just started a topic in the forum:
https://agopengps.discourse.group/t/dual-gps-using-skytraq-receivers/1577

**Comment by farmerbriantee** [comment]
Done manually

**Pull request closed without merging**
